# Generated by Django 3.2.9 on 2023-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, height_field=200, upload_to='', width_field=200),
        ),
    ]
