# Generated by Django 3.2.18 on 2023-04-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actor_image',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='score',
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
