# Generated by Django 4.1 on 2023-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
