# Generated by Django 4.1 on 2023-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
