# Generated by Django 3.1.7 on 2023-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0003_auto_20230416_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.BooleanField(choices=[('Red', 'RED TEAM'), ('Blue', 'BLUE TEAM')], default='RED TEAM'),
        ),
    ]
