# Generated by Django 3.1.7 on 2023-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0004_auto_20230416_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.BooleanField(choices=[(True, 'RED TEAM'), (False, 'BLUE TEAM')], default='RED TEAM'),
        ),
    ]
